### PR TITLE
Extending the academic_term_end_From_sis to 2 week

### PR DESCRIPTION
**Pull request by pushyamig**
Extending the sis academic term data to 2 week using SQL functions

### CODE REVIEW

**Comment by pushyamig** [comment]
This is the change that will be added to Prod release for SSV

**Comment by zqian** [comment]
Unizin has le_term_end_date (set by T&L team inside Canvas, usually just one day before the next term starts), and term_end_date(which is populated by SIS feed). 

The latter right now is the term class end date, instead of exam end date. Hema just sent an email to verify whether the data warehouse team can use exam end date instead. If they cannot make such change, we will use the le_term_end_date instead, to be consistent with Canvas definitions.

Stay tuned.

**Comment by pushyamig** [comment]
@zqian , Last time I checked the problem with `le_term_end_date` is that some of the past terms are set to future dates. when the logic for pulling current terms dates written the past terms were also picked up. So we opted for sis_Term_date.

I don't know if CAnvas term dates are altered now, but using `le_term_end_date` is not very straight forward.

**Comment by zqian** [comment]
OK. Looks like those are the sequence steps that the functional team took:

1. set the current term(e.g. Fall 2023) end date to one day before the next term (Winter 2024) starts
2. once the next term (e.g. Winter 2024) started, extend the current term (e.g. Fall 2023) end term to 10 years later

So I agree we cannot rely on the le_term_end_date since it could be 10 years later. 

Let's wait to see whether Jamie's team can update the SIS feed to use "exam end date" instead of "class end date"

**Comment by pushyamig** [comment]
This PR can be closed since changes are included with this PR #13

**Pull request closed without merging**
